### ISSUE TITLE
Emoji Sequence Whitelist

### ISSUE THREAD

**Issue by djstrong** [adraffy/ensip-norm#1]
How Emoji Sequence Whitelist have been prepared? Is it just an example or it has final content (3 flags and wrestlings)?

**Comment by adraffy** [comment]
It is a list of non-RGI fully-qualified emoji sequences that are well-supported on most platforms (Mac, Win, iOS, Android) selected by me.  It ultimately should be expanded by the ENS DAO as platform support improves.

In an earlier [ens-normalize.js branch, there was a JSON file](https://github.com/adraffy/ens-normalize.js/blob/before-ensip/test/data/emojipedia-missing-zwj-20220508.json) that contains non-RGI emoji from Emojipedia.  Another potential source was a recent [Microsoft Emoji](https://blog.emojipedia.org/diverse-emoji-families-come-to-windows/) update.

FYI: A whitelist is necessary because [`💩ZWJ💩`](https://adraffy.github.io/ens-normalize.js/test/resolver.html#%F0%9F%92%A9%E2%80%8D%F0%9F%92%A9.eth) is a perfectly valid UTS-51 emoji sequence but visually identical to `💩💩`.
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/225900/186052235-37152a3b-161f-4056-a346-b5d7a78e1932.png">

**Comment by adraffy** [comment]
RGI ZWJ sequences:
https://www.unicode.org/Public/emoji/14.0/emoji-zwj-sequences.txt

RGI Emoji:
https://www.unicode.org/Public/emoji/14.0/emoji-sequences.txt
`Basic_Emoji` (that are default Emoij Presentation)
`Emoji_Keycap_Sequence`
`RGI_Emoji_Modifier_Sequence`

By historical accident, I considered `RGI_Emoji_Tag_Sequence` as less safe (since the spec allows arbitrary tag payloads which render invisibly) so they're on the whitelist instead of included by default.

Since EIP-137 allowed single regional indicators, `RGI_Emoji_Flag_Sequence` isn't necessary. 

Note: there is a potential display issue with pairs of regional indicators that collapse into a flag.  Depending on the platform, `🇺🇸 [1F1FA 1F1F8]`, when formatted with `FE0F` (eg. `[1F1FA FE0F 1F1F8 FE0F]`, will render as letters (Mac) or a flag (Windows).

**Comment by adraffy** [comment]
I updated the ENSIP to make this more clear.  All elements of `emoji.json` are now outlined in the ENSIP.
https://github.com/adraffy/ensip-norm/blob/201d440b42aebd64f037a6df112e4d8d975cb5c0/draft.md#derivation-of-emojijson

I moved all the single-codepoint default text-presentation emoji from `chars.json` to `emoji.json`.

I also removed `RGI_Emoji_Tag_Sequence` from the whitelist, so the appendix whitelist only contains sequences that are non-RGI.
